### ISSUE TITLE
error when using pdf files

### ISSUE THREAD

**Issue by scalar27** [DrewThomasson/doc2interview#1]
Thanks for the cool repo!  I can't this to work with local pdf files, although URL's seem to work.   I get this error:

ERROR:root:can only concatenate str (not "NoneType") to str

along with:

ERROR:root:Failed to fetch text from URL: Article `download()` failed with Invalid URL

and some very long paths on my local disk.

**Comment by DrewThomasson** [comment]
Oh yeah, the PDF file upload is broken right now.

**Comment by DrewThomasson** [comment]
I'll probably get around to fixing it on my end when I have time.

**Comment by DrewThomasson** [comment]
Just pushed a fix

both pdf and links should work in the gui now :)




Also improved the prompting system, should follow the prompt better now.

IE, made it give the prompt before and after the document 

Like this:

ollama_input = Prompt + Document_text + Prompt
